In [ ]:
import pandas as pd
df = pd.DataFrame({'x':[0,1,2,3,4],'y':[1,3,5,7,9]})

In [ ]:
df.head()

x  y
0  0  1
1  1  3
2  2  5
3  3  7
4  4  9

In [ ]:
x = df[['x']]
y = df['y']

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [ ]:
model.coef_

array([2.])

In [ ]:
model.intercept_

1.0

In [ ]:
print(f'f(x) = {int(model.coef_[0])} * x+{int(model.intercept_)}')

f(x) = 2 * x+1


In [ ]:
model.predict([[5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.])

In [ ]:
df = pd.read_csv('auto-mpg.data',names =['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']
 ,delim_whitespace=True)

In [ ]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                   car_name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [ ]:
df = df[df['horsepower'] != '?']

In [ ]:
df.shape

(392, 9)

In [ ]:
#step1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
#step 2
df = pd.read_csv('auto-mpg.data',names =['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']
 ,delim_whitespace=True)

In [ ]:
df = df[df['horsepower'] != '?']

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [ ]:
#step 3
X = df[['cylinders', 'displacement', 'horsepower', 'weight','acceleration', 'model_year', 'origin']]
y = df['mpg']

In [ ]:
#step 4
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=131) #hyper parameter tuning

In [ ]:
X_train.head()

cylinders  displacement horsepower  weight  acceleration  model_year  \
3            8         304.0      150.0  3433.0          12.0          70   
18           4          97.0      88.00  2130.0          14.5          70   
376          4          91.0      68.00  2025.0          18.2          82   
248          4          91.0      60.00  1800.0          16.4          78   
177          4         115.0      95.00  2694.0          15.0          75   

     origin  
3         1  
18        3  
376       3  
248       3  
177       2

In [ ]:
#step 5
lr = LinearRegression()

In [ ]:
#step 6
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
lr.predict([[8	,307.0,	130.0,	3504.0,	12.0	,70,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.15022091])